name: Node.js Package

on:
  push:
    paths:
      - 'package.json'
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@Deep-Codes'
      - run: yarn
      - run: yarn build
      - run: npm publish
      - run: npm build-docs
      - run: npm publish-docs
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
